services:
  kitchie:
    container_name: kitchie
    image: ghcr.io/nikhilweee/kitchie:latest
    restart: unless-stopped
    volumes:
      - /mnt/storage/kitchie:/app/data
    environment:
      DATABASE_URL: /app/data/kitchie.db
    networks:
      - proxyman_default

networks:
  proxyman_default:
    external: true
